CREATE TYPE "public"."inscripcion_estado" AS ENUM('recibida', 'procesada', 'duplicada', 'requiere_revision', 'error', 'anulada');--> statement-breakpoint
CREATE TYPE "public"."variante_formulario" AS ENUM('a', 'b', 'c');--> statement-breakpoint
CREATE TABLE "inscripciones" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"numero" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "inscripciones_numero_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"comunicacion_id" uuid,
	"token_hash" text,
	"variante" "variante_formulario" DEFAULT 'a' NOT NULL,
	"viaje_id" uuid,
	"nombre" text NOT NULL,
	"apellido" text NOT NULL,
	"fecha_nacimiento" date NOT NULL,
	"dni" text NOT NULL,
	"numero_pasaporte" text NOT NULL,
	"fecha_vencimiento_pasaporte" date NOT NULL,
	"telefono_alumno" text,
	"email_alumno" text,
	"alergias_salud" text,
	"tutor1_nombre" text NOT NULL,
	"tutor1_celular" text NOT NULL,
	"tutor1_email" text NOT NULL,
	"preferencias_alojamiento" text,
	"nivel_ingles_autoevaluacion" text,
	"estado" "inscripcion_estado" DEFAULT 'recibida' NOT NULL,
	"alumno_id" uuid,
	"motivo" text,
	"consentimiento_version" text NOT NULL,
	"consentimiento_texto_hash" text NOT NULL,
	"consentimiento_el" timestamp NOT NULL,
	"borrado_el" timestamp,
	"borrado_por" uuid,
	"motivo_borrado" text,
	"datos_purgados_el" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "inscripciones_numero_unique" UNIQUE("numero")
);
--> statement-breakpoint
ALTER TABLE "prospecto_comunicaciones" ADD COLUMN "invitacion_token_hash" text;--> statement-breakpoint
ALTER TABLE "prospecto_comunicaciones" ADD COLUMN "invitacion_viaje_id" uuid;--> statement-breakpoint
ALTER TABLE "prospecto_comunicaciones" ADD COLUMN "invitacion_variante" "variante_formulario";--> statement-breakpoint
ALTER TABLE "prospecto_comunicaciones" ADD COLUMN "invitacion_expira_el" timestamp;--> statement-breakpoint
ALTER TABLE "prospecto_comunicaciones" ADD COLUMN "invitacion_revocada_el" timestamp;--> statement-breakpoint
ALTER TABLE "prospecto_comunicaciones" ADD COLUMN "invitacion_lote_id" uuid;--> statement-breakpoint
ALTER TABLE "prospecto_comunicaciones" ADD COLUMN "invitacion_reservado_el" timestamp;--> statement-breakpoint
ALTER TABLE "inscripciones" ADD CONSTRAINT "inscripciones_comunicacion_id_prospecto_comunicaciones_id_fk" FOREIGN KEY ("comunicacion_id") REFERENCES "public"."prospecto_comunicaciones"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inscripciones" ADD CONSTRAINT "inscripciones_viaje_id_viajes_id_fk" FOREIGN KEY ("viaje_id") REFERENCES "public"."viajes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inscripciones" ADD CONSTRAINT "inscripciones_alumno_id_alumnos_id_fk" FOREIGN KEY ("alumno_id") REFERENCES "public"."alumnos"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_inscripcion_comunicacion" ON "inscripciones" USING btree ("comunicacion_id") WHERE "inscripciones"."estado" <> 'anulada';--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_inscripcion_dni_viva" ON "inscripciones" USING btree ("dni") WHERE "inscripciones"."estado" in ('recibida', 'requiere_revision');--> statement-breakpoint
CREATE INDEX "idx_inscripciones_estado_creado" ON "inscripciones" USING btree ("estado","created_at");--> statement-breakpoint
ALTER TABLE "prospecto_comunicaciones" ADD CONSTRAINT "prospecto_comunicaciones_invitacion_viaje_id_viajes_id_fk" FOREIGN KEY ("invitacion_viaje_id") REFERENCES "public"."viajes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_alumnos_canal_alta" ON "alumnos" USING btree ("canal_alta");--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_prospecto_com_invitacion_token" ON "prospecto_comunicaciones" USING btree ("invitacion_token_hash");--> statement-breakpoint
CREATE INDEX "idx_prospecto_com_lote" ON "prospecto_comunicaciones" USING btree ("invitacion_lote_id","estado");